### ISSUE TITLE
README instructions & minigameMasterList.save

### ISSUE THREAD

**Issue by bbradt** [rhiannanberry/GameGameGameGame#1]
Hi! 
I was unable to add a game onto the main menu without deleting the `minigameMasterList.save`  file in the main Assets folder.  As long as this file exists, the PersistentDataManager attempts to load it, and will not instantiate a new list from the `scriptableObjectMinigames` field, which is what you recommend we alter in the README.

I recommend either removing that `minigameMasterList.save` file from the repo, or changing the logic in the PersistentDataManager, so that it will load from the `scriptableObjectMinigames` field, rather than preferring the `minigameMasterList.save`.

The relevant functions in PersistentDataManager _(comments mine)_ are:
```csharp
   public void SaveMinigameMasterList() {
        if (minigameMasterList != null) {
            FileSaveUtil.SaveData<MinigameList>("minigameMasterList", minigameMasterList);
        }
    }

    private void LoadMinigameMasterList() {
        // prefers loading from serialized minigameMasterList
        minigameMasterList = FileSaveUtil.LoadData<MinigameList>("minigameMasterList"); 
        if (minigameMasterList == null) {
            // only if minigameMasterList.save wasn't loadable, create from the field
            minigameMasterList = new MinigameList(scriptableObjectMinigames);
        }
    }
```

As such the current README instructions won't work for adding a game into the menu, but fixing this issue should make them work :)

**Comment by rhiannanberry** [comment]
Hey, thanks for catching this! PersistentDataManager needs to preferentially load the save data, but I do think it's a good idea to remove the save from the repo via the gitignore. That still presents the issue of devs maybe not understanding why their game details aren't updating if a new save gets generated, though.

To remedy this it might be valuable to add a something about that in the README, and perhaps also a button in the unity editor workspace like "Clear Save Data" or "Refresh Games List" that essentially just deletes any save file that has previously been generated. And/or a way to toggle saving while running in the editor, so we don't have to delete a local save every time we want to update a minigame scriptable object or add a game to the list. 

I've recorded this issue and possible remedies in the following trello ticket: https://trello.com/c/UV2Ss3OJ

**Comment by bbradt** [comment]
ok! I'll add more comments to the Trello card to keep discussion there, and we can just update this issue when it's resolved!
